-- Generated by Oracle SQL Developer Data Modeler 4.0.0.833
--   at:        2016-12-12 18:24:56 EST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP DATABASE IF EXISTS Catering;

CREATE DATABASE Catering;
USE Catering;

CREATE TABLE Client
  (
    client_Id         INT(6) PRIMARY KEY NOT NULL ,
    client_First_Name varchar (50) ,
    client_Last_Name  varchar (50) ,
    client_Phone      varchar (12) ,
    client_Street     varchar (50) ,
    client_Zipcode    INT(6) NOT NULL
  ) ;

CREATE TABLE ZipCode
  (
    zipCode    INTEGER NOT NULL PRIMARY KEY,
    zip_City	varchar (50) ,
    zip_State 	varchar (50) 
  ) ;
  

        
CREATE TABLE Events
  (
    event_Id                 INTEGER NOT NULL PRIMARY KEY ,
    event_Name               varchar (50) ,
    event_Date               DATE ,
    event_Type               varchar (50) ,
    event_Start_Time         timestamp ,
    event_Location_Id        INT NOT NULL ,
    event_Guest_Number       INT ,
    event_NumberOfWaiters    INT ,
    event_NumberOfBartenders INT ,
    event_Linen_Id           INT NOT NULL ,
    event_Food_Id            INT NOT NULL ,
    event_Florist_Id         INT NOT NULL ,
    event_Music_Id           INT NOT NULL ,
    event_Entertainer_Id     INT NOT NULL ,
    event_Photographer_Id    INT NOT NULL ,
    event_Client_Id          INT NOT NULL ,
    event_Cost               INT
  ) ;

CREATE TABLE Florist
  (
    florist_Id    INTEGER NOT NULL PRIMARY KEY,
    florist_Name  varchar(50) ,
    florist_Phone varchar(12) ,
    florist_Price INT
  ) ;


CREATE TABLE Food
  (
    food_Id          INT NOT NULL PRIMARY KEY,
    food_Description varchar (250) ,
    food_Price       INT
  ) ;

CREATE TABLE Linen
  (
    linen_Id     INT NOT NULL PRIMARY KEY,
    linen_Colour varchar(50) ,
    linen_Price  INT
  ) ;

CREATE TABLE Location
  (
    location_Id      INT NOT NULL PRIMARY KEY,
    location_Name    varchar (50 ) ,
    location_Street  varchar (50 ) ,
    location_Zipcode INT NOT NULL
  ) ;

CREATE TABLE Music
  (
    music_Id      INT NOT NULL PRIMARY KEY,
    music_Contact varchar (12) ,
    music_Price   INT ,
    music_Type    INT
  ) ;

CREATE TABLE Photographer
  (
    photographer_Id    INT NOT NULL PRIMARY KEY,
    photographer_Name  varchar (50) ,
    photographer_Phone varchar (12) ,
    photographer_Price INT
  ) ;



CREATE TABLE Entertainer
  (
    entertainer_Id    INT NOT NULL PRIMARY KEY,
    entertainer_Name  varchar (50) ,
    entertainer_Phone varchar (12) ,
    entertainer_Type  varchar (50) ,
    entertainer_Price INT
  ) ;
  
ALTER TABLE Client ADD CONSTRAINT Client_ZipCode_FK FOREIGN KEY ( client_Zipcode ) REFERENCES ZipCode ( zipCode ) ;

ALTER TABLE Events ADD CONSTRAINT Events_Client_FK FOREIGN KEY ( event_Client_Id ) REFERENCES Client ( client_Id ) ;

ALTER TABLE Events ADD CONSTRAINT Events_Entertainer_FK FOREIGN KEY ( event_Entertainer_Id ) REFERENCES Entertainer ( entertainer_Id ) ;

ALTER TABLE Events ADD CONSTRAINT Events_Florist_FK FOREIGN KEY ( event_Florist_Id ) REFERENCES Florist ( florist_Id ) ;

ALTER TABLE Events ADD CONSTRAINT Events_Food_FK FOREIGN KEY ( event_Food_Id ) REFERENCES Food ( food_Id ) ;

ALTER TABLE Events ADD CONSTRAINT Events_Linen_FK FOREIGN KEY ( event_Linen_Id ) REFERENCES Linen ( linen_Id ) ;

ALTER TABLE Events ADD CONSTRAINT Events_Location_FK FOREIGN KEY ( event_Location_Id ) REFERENCES Location ( location_Id ) ;

ALTER TABLE Events ADD CONSTRAINT Events_Music_FK FOREIGN KEY ( event_Music_Id ) REFERENCES Music ( music_Id ) ;

ALTER TABLE Events ADD CONSTRAINT Events_Photographer_FK FOREIGN KEY ( event_Photographer_Id ) REFERENCES Photographer ( photographer_Id ) ;

ALTER TABLE Location ADD CONSTRAINT Location_ZipCode_FK FOREIGN KEY ( location_Zipcode ) REFERENCES ZipCode ( zipCode ) ;

-- Create indexs on FK

CREATE UNIQUE INDEX ClientID_IND ON Events (event_Client_Id);
CREATE UNIQUE INDEX LocID_IND ON Events (event_Location_Id);
CREATE UNIQUE INDEX PhotoID_IND ON Events (event_Photographer_Id);
CREATE UNIQUE INDEX Entr_IND ON Events (event_Entertainer_Id);
CREATE UNIQUE INDEX Flor_IND ON Events (event_Florist_Id);
CREATE UNIQUE INDEX Musi_IND ON Events (event_Music_Id);
CREATE UNIQUE INDEX Linen_IND ON Events (event_Linen_Id);
CREATE UNIQUE INDEX Food_IND ON Events (event_Food_Id);

-- Add constraints on tables

ALTER TABLE Events ADD CONSTRAINT event_key UNIQUE (event_Client_Id, event_Date, event_Start_Time);

ALTER TABLE Client ADD CONSTRAINT client_name UNIQUE (client_First_Name);

ALTER TABLE Location ADD CONSTRAINT unique_location UNIQUE (location_Name);